image:
  width: 1024
  height: 1024

directories:
  skin: "/Users/dylanhawley/Projects/crafty-skins/data/raw/skins/"
  target: "/Users/dylanhawley/Projects/crafty-skins/data/raw/input/"
  output: "/Users/dylanhawley/Projects/crafty-skins/data/processed/"

perspectives:
  - x: "left"
    y: "front"
    z: "up"
    scaling_factor: 20
  - x: "right"
    y: "back"
    z: "up"
    scaling_factor: 20
  - x: "left"
    y: "back"
    z: "down"
    scaling_factor: 20
  - x: "right"
    y: "front"
    z: "down"
    scaling_factor: 20